import type { Metadata } from "next";

import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { Syne } from "@/utils/customFont";
import { sidebar } from "@/data/sidebar";
import { ScrollArea } from "@radix-ui/react-scroll-area";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${Syne.variable} font-normal  w-full! min-h-screen bg-[#f9f9f9]`}>
        <div className="flex !w-full items-start grow-1 ">
          <aside className="hidden bg-white min-w-[350px] h-screen overflow-y-auto px-[70px] border-r bg-background md:sticky top-0 md:flex">
            <ScrollArea className="flex flex-col items-start justify-center pt-2.5 w-full">
              <Image src={'/dark.png'} alt="Logo" width={150} height={30} />
              <ol className="flex flex-col items-start py-[50px] w-full">
                {
                  sidebar.map((item, i) => (
                    <li className="mb-2.5 uppercase w-full" key={i}>
                      <Link className="text-gray-1 inline-block font-medium w-full text-[13px] hover:text-black transition duration-200" href={item.path}>{item.name}</Link>
                    </li>
                  ))
                }
              </ol>

              <p className="text-black/50">© 2024 Kioto</p>
              <p className="text-black/50">Created by <Link className="text-black/60 hover:text-black transition duration-300" href={'/'}>Marketify</Link></p>
            </ScrollArea>
          </aside>
            {children}
        </div>
      </body>
    </html>
  );
}
