import type { Metadata } from "next";

import "./globals.css";
import { Syne } from "@/utils/customFont";
import SideBar from "@/components/Sidebar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{children: React.ReactNode;}>) {
  
  return (
    <html lang="en">
      <body className={`${Syne.variable} font-normal  w-full! min-h-screen bg-[#f9f9f9]`}>
        <div className="flex !w-full items-start grow-1 ">
          <SideBar/>
          {children}
        </div>
      </body>
    </html>
  );
}
